# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 14 10:19:05 2025
# ------------------------------------------------

package:
  name: charset-normalizer
  version: 3.4.4
source:
  url: https://pypi.org/packages/source/c/charset-normalizer/charset_normalizer-3.4.4.tar.gz
  sha256: 94537985111c35f28720e43603b8e7b43a6ecfb2ce1d3058bbe955b73404e21a
build:
  number: '0'
  noarch: python
  entry_points:
    - normalizer = charset_normalizer.cli:cli_detect
  script: /home/conda/feedstock_root/build_artifacts/charset-normalizer_1760437218288/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libexpat 2.7.1 hecca717_0
    - libffi 3.5.2 h9ec8514_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - pip 25.2 pyh8b19718_0
    - python 3.10.19 hd994cfb_1_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.10
test:
  imports:
    - charset_normalizer
  commands:
    - pip check
    - normalizer --help
  requires:
    - pip
    - python 3.10.*
about:
  home: https://github.com/Ousret/charset_normalizer
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
  license: MIT
  license_file:
    - LICENSE
    - data/NOTICE.md
extra:
  recipe-maintainers:
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251014.2.1
  remote_url: https://github.com/conda-forge/charset-normalizer-feedstock
  sha: 574b489699ce8b0db3d097e6a4ca71c91250a4be
