# This file created by conda-build 25.7.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Sep 13 06:22:31 2025
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  patches:
    - patches/0001-GH-100-Replace-unittest.makeSuite-with-unittest.defaultTest.patch
build:
  number: '3'
  script: /Users/runner/miniforge3/conda-bld/pycosat_1757744682161/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: py312h163523d_3
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cctools_osx-64 1024.3 haa85c18_1
    - cctools_osx-arm64 1024.3 h65996a6_1
    - clang 19.1.7 default_h1323312_4
    - clang-19 19.1.7 default_hc369343_4
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_h1c12a56_4
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - cross-python_osx-arm64 3.12 52_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 955.13 hf1c22e8_1
    - ld64_osx-arm64 955.13 h59013cd_1
    - libclang-cpp19.1 19.1.7 default_hc369343_4
    - libcxx 21.1.1 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_1
    - libexpat 2.7.1 h21dd04a_0
    - libffi 3.4.6 h281671d_1
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.50.4 h39a8b3b_0
    - libxml2 2.14.6 h7b7ecba_2
    - libxml2-16 2.14.6 ha1d9b0f_2
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.2 h6e31bce_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.11 h9ccd52b_0_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - libexpat 2.7.1 hec049ff_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.50.4 h4237e3c_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.2 he92f556_0
    - pip 25.2 pyh8b19718_0
    - python 3.12.11 hc22306f_0_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h892fb3f_2
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  requires:
    - pip
  imports:
    - pycosat
  commands:
    - pip check
    - python test_package.py "0.6.6"
about:
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - COPYRIGHT
    - LICENSE
  summary: Bindings to picosat (a SAT solver)
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  doc_url: https://pypi.python.org/pypi/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  dev_url: https://github.com/conda/pycosat
extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - nehaljwani
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250913.1.1
  remote_url: https://github.com/conda-forge/pycosat-feedstock
  sha: 42d6b5b0a2382e83eef2e4ba12b519a151386102
