# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: libxml2-16
  version: 2.15.1
source:
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.15.1/libxml2-v2.15.1.tar.gz
  sha256: 0a5ebf8fa131585748d661ae692503483aff39d9b29b6c4b342cd80d422f246c
build:
  number: '0'
  noarch: false
  noarch_python: false
  python_version_independent: false
  string: h8eac4d7_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 19.1.7 h4c5f930_25
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
  host:
    - libiconv 1.18 h23cfdf5_2
    - liblzma 5.8.1 h39f12f2_2
    - liblzma-devel 5.8.1 h39f12f2_2
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run_constrained:
    - icu <0.0a0
    - libxml2 2.15.1
  run:
    - __osx >=11.0
    - libiconv >=1.18,<2.0a0
    - liblzma >=5.8.1,<6.0a0
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libxml2.16.dylib
about:
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  doc_url: http://xmlsoft.org/html/index.html
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/devhelp/index.html
  dev_url: https://git.gnome.org/browse/libxml2/
extra:
  feedstock-name: libxml2
  recipe-maintainers:
    - gillins
    - isuruf
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251020.1.1
  remote_url: https://github.com/conda-forge/libxml2-feedstock
  sha: 2a67507d31d7b385dd7421e32e5aa8289bcc9a0e
