# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.51.1
source:
  url: https://www.sqlite.org/2025/sqlite-autoconf-3510100.tar.gz
  sha256: 4f2445cd70479724d32ad015ec7fd37fbb6f6130013bd4bfbc80c32beb42b7e0
build:
  run_exports:
    - libsqlite >=3.51.1,<4.0a0
  number: 1
  string: h1b79a29_1
requirements:
  build:
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h3b512aa_2
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h5cc7f4e_2
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_2
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_28
    - clang_osx-arm64 19.1.7 h1728699_28
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - ld64_osx-64 956.6 llvm19_1_h466f870_2
    - ld64_osx-arm64 956.6 llvm19_1_hcfa1dea_2
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcxx 21.1.8 h3d58e20_0
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_4
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.0 h230baf5_0
    - sdkroot_env_osx-arm64 14.5 hfa17104_3
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1600.0.11.8 h8d8e812_0
    - zstd 1.5.7 h3eecb57_6
  host:
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
    - test -f $PREFIX/lib/pkgconfig/sqlite3.pc
about:
  home: http://www.sqlite.org/
  license: blessing
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite
extra:
  recipe-maintainers:
    - flaviomartins
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251221.2.1
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: 5daa04a397920d915ccc85d267682d07a62cd7c8
