# This file created by conda-build 25.7.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Sep  1 19:14:20 2025
# ------------------------------------------------

package:
  name: jsonpointer
  version: 3.0.0
source:
  url: https://pypi.org/packages/source/j/jsonpointer/jsonpointer-3.0.0.tar.gz
  sha256: 2b2d729f2091522d61c3b31f82e11870f60b68f43fbc705cb76bf4b832af59ef
build:
  script: /Users/runner/miniforge3/conda-bld/jsonpointer_1756754188614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv
  number: '2'
  string: py312h81bd7bf_2
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cctools_osx-64 1024.3 hb0509f7_1
    - cctools_osx-arm64 1024.3 hc5025d4_1
    - clang 21.1.0 default_hb6a0502_0
    - clang-21 21.1.0 default_hd2a208e_0
    - clang_impl_osx-arm64 21.1.0 hbaa0749_25
    - clang_osx-arm64 21.1.0 h1728699_25
    - clangxx 21.1.0 default_h4c96677_0
    - clangxx_impl_osx-arm64 21.1.0 h4f30fa3_25
    - compiler-rt 21.1.0 h6456c34_0
    - compiler-rt_osx-64 21.1.0 hf09ce48_0
    - cross-python_osx-arm64 3.12 52_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 955.13 h2bd93d8_1
    - ld64_osx-arm64 955.13 h436a7a2_1
    - libclang-cpp21.1 21.1.0 default_hd2a208e_0
    - libcxx 21.1.0 h3d58e20_1
    - libcxx-devel 21.1.0 h7c275be_1
    - libexpat 2.7.1 h21dd04a_0
    - libffi 3.4.6 h281671d_1
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm21 21.1.0 h9b4ebcc_0
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.50.4 h39a8b3b_0
    - libxml2 2.13.8 he1bc88e_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 21.1.0 hc040464_0
    - llvm-tools-21 21.1.0 h0167baa_0
    - lz4-c 1.10.0 h240833e_1
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.2 h6e31bce_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.11 h9ccd52b_0_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - libexpat 2.7.1 hec049ff_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.50.4 h4237e3c_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.2 he92f556_0
    - pip 25.2 pyh8b19718_0
    - python 3.12.11 hc22306f_0_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h892fb3f_2
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  imports:
    - jsonpointer
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/stefankoegl/python-json-pointer
  summary: Identify specific nodes in a JSON document (RFC 6901)
  license: BSD-3-Clause
  license_file: LICENSE.txt
extra:
  recipe-maintainers:
    - anguslees
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250901.1.1
  remote_url: https://github.com/conda-forge/jsonpointer-feedstock
  sha: 9feadcae74a0f981ac7e63e1a138cb1bb57a60d1
