# This file created by conda-build 25.11.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Nov 25 14:34:32 2025
# ------------------------------------------------

package:
  name: conda-libmamba-solver
  version: 25.11.0
source:
  url: https://github.com/conda/conda-libmamba-solver/archive/25.11.0.tar.gz
  sha256: a187016471bc561405ea66266f26c0f81637f6e85b4d8663a6724717dc715f50
  folder: src/
build:
  noarch: python
  number: '0'
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=25.11.0
  script: /home/conda/feedstock_root/build_artifacts/conda-libmamba-solver_1764081326783/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install src/ -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - editables 0.5 pyhd8ed1ab_1
    - hatch-vcs 0.5.0 pyhd8ed1ab_0
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - icu 75.1 he02047a_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - ld_impl_linux-64 2.45 default_hbd61a6d_104
    - libexpat 2.7.3 hecca717_0
    - libffi 3.5.2 h9ec8514_0
    - libgcc 15.2.0 he0feb66_12
    - libgcc-ng 15.2.0 h69a702a_12
    - libgomp 15.2.0 he0feb66_12
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.51.0 hee844dc_0
    - libstdcxx 15.2.0 h934c35e_12
    - libstdcxx-ng 15.2.0 hdf11a46_12
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.6.0 h26f9b46_0
    - packaging 25.0 pyh29332c3_1
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 25.3 pyh8b19718_0
    - pluggy 1.6.0 pyhd8ed1ab_0
    - python 3.10.19 h3c07f61_2_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 9.2.2 pyhd8ed1ab_0
    - tk 8.6.13 noxft_ha0e22de_103
    - tomli 2.3.0 pyhcf101f3_0
    - trove-classifiers 2025.11.14.15 pyhd8ed1ab_0
    - typing-extensions 4.15.0 h396c80c_0
    - typing_extensions 4.15.0 pyhcf101f3_0
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - boltons >=23.0.0
    - conda >=25.9
    - libmambapy >=2.0.0
    - msgpack-python >=1.1.1
    - python >=3.10
    - requests >=2.28.0,<3
    - zstandard >=0.15
test:
  requires:
    - python 3.10.*
  imports:
    - conda_libmamba_solver
  commands:
    - conda create -n test --dry-run scipy --solver=libmamba
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy
about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/
extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251125.3.1
  remote_url: https://github.com/conda-forge/conda-libmamba-solver-feedstock
  sha: ace74479e4b734f9eeab0f05c8f9ad50ebb7eb5c
