# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: python
  version: 3.13.11
source:
  - url: https://www.python.org/ftp/python/3.13.11/Python-3.13.11.tar.xz
    md5: 4c3517dd8b1fd76377dcb3e5e8f71ad6
    patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      - patches/0009-cross-compile-darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0020-Don-t-checksharedmods-if-cross-compiling.patch
      - patches/0021-Override-configure-LIBFFI.patch
      - patches/0022-Unvendor-libmpdec.patch
      - patches/0023-Brand-conda-forge.patch
      - patches/0024-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
      - patches/0025-Search-LLVM_ROOT-for-llvm-binaries.patch
build:
  number: 100
  activate_in_script: true
  no_link: null
  ignore_run_exports_from:
    - clangxx_osx-arm64 19.*
    - xorg-libx11
    - xorg-xorgproto
  detect_binary_files_with_prefix: true
  skip_compile_pyc:
    - '*.py'
  string: hfc2f54d_100_cp313
  python_site_packages_path: lib/python3.13/site-packages
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.13.* *_cp313
  track_features: null
  script_env:
    - PY_FREETHREADING=no
    - PY_INTERP_DEBUG=no
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h3b512aa_1
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h5cc7f4e_1
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_1
    - clang 19.1.7 default_h1323312_5
    - clang-18 18.1.8 default_hc369343_16
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_27
    - clang_osx-arm64 19.1.7 h1728699_27
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_27
    - clangxx_osx-arm64 19.1.7 h1728699_27
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - expat 2.7.3 heffb93a_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 956.6 llvm19_1_h466f870_1
    - ld64_osx-arm64 956.6 llvm19_1_hcfa1dea_1
    - libclang-cpp18.1 18.1.8 default_hc369343_16
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcxx 21.1.7 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_2
    - libcxx-headers 19.1.7 h707e725_2
    - libexpat 2.7.3 heffb93a_0
    - libffi 3.5.2 h750e83c_0
    - libiconv 1.18 h57a12c2_2
    - libllvm18 18.1.8 default_hc369343_11
    - libllvm19 19.1.7 h56e7563_2
    - libltdl 2.4.3a h240833e_0
    - liblzma 5.8.1 hd471939_2
    - liblzma-devel 5.8.1 hd471939_2
    - libsqlite 3.51.1 h6cc646a_0
    - libtool 2.5.4 h240833e_0
    - libxml2 2.15.1 h7b7ecba_0
    - libxml2-16 2.15.1 ha1d9b0f_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-18 18.1.8 default_hc369343_11
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_4
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.4 h230baf5_0
    - pkg-config 0.29.2 hf7e621a_1009
    - readline 8.2 h7cca4af_2
    - sdkroot_env_osx-arm64 14.5 hfa17104_3
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1600.0.11.8 h8d8e812_0
    - tk 8.6.13 hf689a15_3
    - zlib 1.3.1 hd23fc13_2
    - zstd 1.5.7 h3eecb57_6
  host:
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - expat 2.7.3 haf25636_0
    - libexpat 2.7.3 haf25636_0
    - libffi 3.5.2 he5f378a_0
    - liblzma 5.8.1 h39f12f2_2
    - liblzma-devel 5.8.1 h39f12f2_2
    - libmpdec 4.0.0 h99b78c6_0
    - libmpdec-devel 4.0.0 hce30654_0
    - libsqlite 3.51.1 h9a5124b_0
    - libxcb 1.17.0 hdb1d25a_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.4 h5503f6c_0
    - pthread-stubs 0.4 hd74edd7_1002
    - readline 8.2 h1d1bf99_2
    - tk 8.6.13 h892fb3f_3
    - xorg-libx11 1.8.12 h6a5fb8c_0
    - xorg-libxau 1.0.12 hc919400_1
    - xorg-libxdmcp 1.1.5 hc919400_1
    - xorg-xorgproto 2024.1 hd74edd7_1
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - bzip2 >=1.0.8,<2.0a0
    - libexpat >=2.7.3,<3.0a0
    - libffi >=3.5.2,<3.6.0a0
    - liblzma >=5.8.1,<6.0a0
    - libmpdec >=4.0.0,<5.0a0
    - libsqlite >=3.51.1,<4.0a0
    - libzlib >=1.3.1,<2.0a0
    - ncurses >=6.5,<7.0a0
    - openssl >=3.5.4,<4.0a0
    - python_abi 3.13.* *_cp313
    - readline >=8.2,<9.0a0
    - tk >=8.6.13,<8.7.0a0
    - tzdata
test:
  downstreams:
    - cython
    - setuptools
  requires:
    - clang_osx-arm64 19.*
    - clangxx_osx-arm64 19.*
    - cmake
    - macosx_deployment_target_osx-arm64 11.0.*
    - ninja
    - ripgrep
    - xorg-libx11
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/prefix-replacement/*
  commands:
    - python -V
    - python3 -V
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @[^@]*@ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.13.11 --debug-find --trace --debug-output --debug-trycompile
      .
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
    - TERM=xterm >/dev/null python -c "import curses; scr = curses.initscr(); curses.unget_wch('x');
      assert 'x' ==  scr.get_wch()"
about:
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
  description: "Python is a widely used high-level, general-purpose, interpreted,\
    \ dynamic\nprogramming language. Its design philosophy emphasizes code\nreadability,\
    \ and its syntax allows programmers to express concepts in\nfewer lines of code\
    \ than would be possible in languages such as C++ or\nJava. The language provides\
    \ constructs intended to enable clear programs\non both a small and large scale.\n\
    \nWe provide some meta packages for convenience.\nTo get a CPython flavour, use:\n\
    \n    conda install cpython\n\nTo get the freethreading build (i.e. without the\
    \ Global Interpreter Lock - GIL):\n\n    conda install python-freethreading\n\n\
    To get the default build (i.e. with the GIL):\n\n    conda install python-gil\n\
    \nTo enable the use of the experimental JIT compiler in CPython:\n\n    conda\
    \ install python-jit\n\nor set the environment variable PYTHON_JIT=1. Note that\
    \ the JIT support\nis available for x86_64 builds only.\n"
  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/
extra:
  feedstock-name: python
  recipe-maintainers:
    - chrisburr
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251206.1.1
  remote_url: https://github.com/conda-forge/python-feedstock
  sha: d6b6a6373887c8b9e771b0e112ad0dcb920104d5
