# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: simdjson
  version: 4.2.2
source:
  url: https://github.com/simdjson/simdjson/archive/v4.2.2.tar.gz
  sha256: 3efae22cb41f83299fe0b2e8a187af543d3dda93abbb910586f897df670f9eaa
build:
  run_exports:
    - simdjson >=4.2.2,<4.3.0a0
  number: 0
  string: ha7d2532_0
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - c-ares 1.34.5 hf13058a_0
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_osx-64 1024.3 llvm19_1_h3b512aa_9
    - cctools_osx-arm64 1024.3 llvm19_1_h5cc7f4e_9
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - clangxx_osx-arm64 19.1.7 h1728699_25
    - cmake 4.1.2 h29fc008_0
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 955.13 llvm19_1_h466f870_9
    - ld64_osx-arm64 955.13 llvm19_1_hcfa1dea_9
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcurl 8.17.0 h7dd4100_0
    - libcxx 21.1.5 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_1
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.1 h21dd04a_0
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libnghttp2 1.67.0 h3338091_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h58003a5_1
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.13.1 h0ba0a54_0
    - openssl 3.6.0 h230baf5_0
    - rhash 1.4.6 h6e16a3a_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - libcxx 21.1.5 hf598326_0
  run:
    - __osx >=11.0
    - libcxx >=19
test:
  requires:
    - clangxx_osx-arm64 19.*
    - cmake
    - ninja
  files:
    - test/*
  commands:
    - test -f "${PREFIX}/include/simdjson.h"
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
about:
  home: https://simdjson.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  doc_url: https://simdjson.github.io/simdjson/
  dev_url: https://github.com/simdjson/simdjson/
extra:
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251112.2.1
  remote_url: https://github.com/conda-forge/simdjson-feedstock
  sha: bb0b394cc62899b096db9440dc2a342457f716f5
