# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Nov 10 12:01:47 2025
# ------------------------------------------------

package:
  name: pip
  version: '25.3'
source:
  url: https://pypi.org/packages/source/p/pip/pip-25.3.tar.gz
  sha256: 8d0538dbbd7babbd207f261ed969c65de439f6bc9e5dbd3b3b9a77f25d95f343
build:
  noarch: python
  number: '0'
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  string: pyh145f28c_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - flit-core 3.12.0 pyhd8ed1ab_0
    - icu 75.1 he02047a_0
    - ld_impl_linux-64 2.44 h1aa0949_5
    - libexpat 2.7.1 hecca717_0
    - libffi 3.5.2 h9ec8514_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libmpdec 4.0.0 hb9d3cd8_0
    - libsqlite 3.51.0 hee844dc_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libstdcxx-ng 15.2.0 h4852527_7
    - libuuid 2.41.2 he9a06e4_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - python 3.14.0 h32b2ec7_102_cp314
    - python_abi 3.14 8_cp314
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - python >=3.13.0a0
test:
  requires:
    - python 3.13.0.*
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251110.1.1
  remote_url: https://github.com/conda-forge/pip-feedstock
  sha: 96870febe76b7cd0345635414cb27c24ee2ed546
