# This file created by conda-build 25.11.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov 25 13:29:09 2025
# ------------------------------------------------

package:
  name: conda
  version: 25.11.0
source:
  fn: conda-25.11.0.tar.gz
  url: https://github.com/conda/conda/releases/download/25.11.0/conda-25.11.0.tar.gz
  sha256: 62aad5c046936b07e3ea44d6d908f2d94b427049420332def421e9c72ff3961e
  folder: conda-src
build:
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/conda_1764077554327/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install conda-src/ --no-deps --no-build-isolation -vv && /Users/runner/miniforge3/conda-bld/conda_1764077554327/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m conda init --install
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  string: py312h81bd7bf_0
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_osx-64 1024.3 llvm21_1_h81d60ea_9
    - cctools_osx-arm64 1024.3 llvm21_1_h501ec7a_9
    - clang 21.1.6 default_h1323312_0
    - clang-21 21.1.6 default_h9f74b92_0
    - clang_impl_osx-arm64 21.1.6 h26e368e_25
    - clang_osx-arm64 21.1.6 h1728699_25
    - clangxx 21.1.6 default_h1c12a56_0
    - clangxx_impl_osx-arm64 21.1.6 h9650d72_25
    - compiler-rt 21.1.6 h694c41f_0
    - compiler-rt21 21.1.6 he914875_0
    - compiler-rt21_osx-64 21.1.6 he0f92a2_0
    - cross-python_osx-arm64 3.12 54_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - ld64 955.13 h2eed689_9
    - ld64_osx-64 955.13 llvm21_1_h2cc85ee_9
    - ld64_osx-arm64 955.13 llvm21_1_h252d2c3_9
    - libclang-cpp21.1 21.1.6 default_hc369343_0
    - libcxx 21.1.6 h3d58e20_0
    - libcxx-devel 21.1.6 h7c275be_0
    - libcxx-headers 21.1.6 h707e725_0
    - libexpat 2.7.3 heffb93a_0
    - libffi 3.5.2 h750e83c_0
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm21 21.1.6 h56e7563_0
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.51.0 h86bffb9_0
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-openmp 21.1.6 h472b3d1_0
    - llvm-tools 21.1.6 hb0207f0_0
    - llvm-tools-21 21.1.6 h879f4bc_0
    - lz4-c 1.10.0 h240833e_1
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.0 h230baf5_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.12 h74c2667_1_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_3
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - boltons 25.0.0 pyhd8ed1ab_0
    - brotli-python 1.2.0 py312h0dfefe5_1
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - certifi 2025.11.12 pyhd8ed1ab_0
    - cffi 2.0.0 py312h1b4d9a2_1
    - charset-normalizer 3.4.4 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_1
    - editables 0.5 pyhd8ed1ab_1
    - frozendict 2.4.7 py312h4409184_0
    - h2 4.3.0 pyhcf101f3_0
    - hatch-vcs 0.5.0 pyhd8ed1ab_0
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - hpack 4.1.0 pyhd8ed1ab_0
    - hyperframe 6.1.0 pyhd8ed1ab_0
    - icu 75.1 hfee45f7_0
    - idna 3.11 pyhd8ed1ab_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - libcxx 21.1.6 hf598326_0
    - libexpat 2.7.3 haf25636_0
    - libffi 3.5.2 he5f378a_0
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.51.0 h8adb53f_0
    - libzlib 1.3.1 h8359307_2
    - menuinst 2.4.1 py312h81bd7bf_0
    - ncurses 6.5 h5e97a16_3
    - openssl 3.6.0 h5503f6c_0
    - packaging 25.0 pyh29332c3_1
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 25.3 pyh8b19718_0
    - platformdirs 4.5.0 pyhcf101f3_0
    - pluggy 1.6.0 pyhd8ed1ab_0
    - pycparser 2.22 pyh29332c3_1
    - pysocks 1.7.1 pyha55dd90_7
    - python 3.12.12 h18782d2_1_cpython
    - python_abi 3.12 8_cp312
    - readline 8.2 h1d1bf99_2
    - requests 2.32.5 pyhd8ed1ab_0
    - ruamel.yaml 0.18.16 py312h4409184_0
    - ruamel.yaml.clib 0.2.14 py312h4409184_0
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 9.2.2 pyhd8ed1ab_0
    - tk 8.6.13 h892fb3f_3
    - tomli 2.3.0 pyhcf101f3_0
    - tqdm 4.67.1 pyhd8ed1ab_1
    - trove-classifiers 2025.11.14.15 pyhd8ed1ab_0
    - typing-extensions 4.15.0 h396c80c_0
    - typing_extensions 4.15.0 pyhcf101f3_0
    - tzdata 2025b h78e105d_0
    - urllib3 2.5.0 pyhd8ed1ab_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
    - zstandard 0.25.0 py312h37e1c23_1
    - zstd 1.5.7 h6491c7d_2
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=25.4.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=25.9
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  requires:
    - mock
    - pexpect
    - responses
  imports:
    - conda
    - conda_env
  files:
    - commands_to_test.sh
    - test_runner.sh
  downstreams: null
about:
  home: https://conda.io
  license: BSD-3-Clause
  license_file: conda-src/LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  dev_url: https://github.com/conda/conda
extra:
  recipe-maintainers:
    - beeankha
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251125.1.1
  remote_url: https://github.com/conda-forge/conda-feedstock
  sha: 0d5610ff990eca05b2987043e29c92d5412fb9e8
