# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Oct 24 09:54:35 2025
# ------------------------------------------------

package:
  name: menuinst
  version: 2.4.1
source:
  url: https://github.com/conda/menuinst/archive/2.4.1.tar.gz
  sha256: dc656f0f5a85d7e282a869e0e771e7fdab112a54ce95aabe78849dc90fec0f83
build:
  number: '0'
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.4.1
  script:
    - /Users/runner/miniforge3/conda-bld/menuinst_1761299914766/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
      -m pip install . -vv
  entry_points:
    - menuinst = menuinst.cli:main
  string: py312h81bd7bf_0
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - cctools_osx-64 1024.3 llvm21_1_h81d60ea_5
    - cctools_osx-arm64 1024.3 llvm21_1_h501ec7a_5
    - clang 21.1.4 default_h1323312_0
    - clang-21 21.1.4 default_h9f74b92_0
    - clang_impl_osx-arm64 21.1.4 hf420727_25
    - clang_osx-arm64 21.1.4 h1728699_25
    - clangxx 21.1.4 default_h1c12a56_0
    - clangxx_impl_osx-arm64 21.1.4 h304ebd6_25
    - compiler-rt 21.1.4 h694c41f_0
    - compiler-rt21 21.1.4 he914875_0
    - compiler-rt21_osx-64 21.1.4 he0f92a2_0
    - cross-python_osx-arm64 3.12 54_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - ld64 955.13 h2eed689_5
    - ld64_osx-64 955.13 llvm21_1_h2cc85ee_5
    - ld64_osx-arm64 955.13 llvm21_1_h252d2c3_5
    - libclang-cpp21.1 21.1.4 default_hc369343_0
    - libcxx 21.1.4 h3d58e20_0
    - libcxx-devel 21.1.4 h7c275be_0
    - libexpat 2.7.1 h21dd04a_0
    - libffi 3.5.2 h750e83c_0
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm21 21.1.4 h56e7563_0
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.50.4 h39a8b3b_0
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-openmp 21.1.4 h472b3d1_0
    - llvm-tools 21.1.4 hb0207f0_0
    - llvm-tools-21 21.1.4 h879f4bc_0
    - lz4-c 1.10.0 h240833e_1
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.4 h230baf5_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.12 h74c2667_1_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - libexpat 2.7.1 hec049ff_0
    - libffi 3.5.2 he5f378a_0
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.50.4 h4237e3c_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.4 h5503f6c_0
    - packaging 25.0 pyh29332c3_1
    - pip 25.2 pyh8b19718_0
    - python 3.12.12 h18782d2_1_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 9.2.2 pyhd8ed1ab_0
    - setuptools_scm 9.2.2 hd8ed1ab_0
    - tk 8.6.13 h892fb3f_2
    - tomli 2.3.0 pyhcf101f3_0
    - typing-extensions 4.15.0 h396c80c_0
    - typing_extensions 4.15.0 pyhcf101f3_0
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
  run:
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  imports:
    - menuinst
    - menuinst.api
  commands:
    - menuinst --help
    - SP_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_x86_64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_x86_64"
about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
  doc_url: https://conda.github.io/menuinst/
extra:
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251024.1.1
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: b222b5493e1d6ed6671ff440e4d30363609ed0b5
