# This file created by conda-build 25.7.0
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.67.0
source:
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.67.0/nghttp2-1.67.0.tar.gz
  sha256: f61f8b38c0582466da9daa1adcba608e1529e483de6b5b2fbe8a5001d41db80c
build:
  run_exports:
    - libnghttp2 >=1.67.0,<2.0a0
  number: 0
  string: hc438710_0
requirements:
  build:
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cctools_osx-64 1024.3 haa85c18_1
    - cctools_osx-arm64 1024.3 h65996a6_1
    - clang 19.1.7 default_h576c50e_3
    - clang-19 19.1.7 default_h3571c67_3
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_heb2e8d1_3
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - clangxx_osx-arm64 19.1.7 h1728699_25
    - compiler-rt 19.1.7 h52031e2_0
    - compiler-rt_osx-64 19.1.7 hc6f8467_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 955.13 hf1c22e8_1
    - ld64_osx-arm64 955.13 h59013cd_1
    - libclang-cpp19.1 19.1.7 default_h3571c67_3
    - libcxx 21.1.0 h3d58e20_1
    - libcxx-devel 19.1.7 h7c275be_1
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 hc29ff6c_1
    - liblzma 5.8.1 hd471939_2
    - libxml2 2.13.8 he1bc88e_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 h3fe3016_1
    - llvm-tools-19 19.1.7 he90a8e3_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.2 h6e31bce_0
    - pkg-config 0.29.2 hf7e621a_1009
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - c-ares 1.34.5 h5505292_0
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - libcxx 21.1.0 hf598326_1
    - libev 4.33 h93a5062_2
    - libzlib 1.3.1 h8359307_2
    - openssl 3.5.2 he92f556_0
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - c-ares >=1.34.5,<2.0a0
    - libcxx >=19
    - libev >=4.33,<4.34.0a0
    - libev >=4.33,<5.0a0
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.5.2,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
about:
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  doc_url: https://nghttp2.org/documentation/
  dev_url: https://github.com/nghttp2/nghttp2
extra:
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250902.2.1
  remote_url: https://github.com/conda-forge/nghttp2-feedstock
  sha: 37f0feb648d49c4ee44d64bd2840d0914aae8aef
