# This file created by conda-build 25.11.0
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.2.0
source:
  fn: brotli-1.2.0.tar.gz
  url: https://github.com/google/brotli/archive/v1.2.0.tar.gz
  sha256: 816c96e8e8f193b40151dad7e8ff37b1221d019dbcb9c35cd3fadbfe6477dfec
build:
  ignore_run_exports_from:
    - brotli
  number: 1
  string: py312h0dfefe5_1
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - c-ares 1.34.5 hf13058a_0
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_osx-64 1024.3 llvm19_1_h3b512aa_9
    - cctools_osx-arm64 1024.3 llvm19_1_h5cc7f4e_9
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - clangxx_osx-arm64 19.1.7 h1728699_25
    - cmake 4.2.0 h29fc008_0
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - cross-python_osx-arm64 3.12 54_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 955.13 llvm19_1_h466f870_9
    - ld64_osx-arm64 955.13 llvm19_1_hcfa1dea_9
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcurl 8.17.0 h7dd4100_0
    - libcxx 21.1.6 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_1
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.3 heffb93a_0
    - libffi 3.5.2 h750e83c_0
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libnghttp2 1.67.0 h3338091_0
    - libsqlite 3.51.0 h86bffb9_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h58003a5_1
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.13.2 hfc0b2d5_0
    - openssl 3.6.0 h230baf5_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.12 h74c2667_1_cpython
    - readline 8.2 h7cca4af_2
    - rhash 1.4.6 h6e16a3a_1
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_3
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - brotli 1.2.0 h7d5ae5b_1
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - libcxx 21.1.6 hf598326_0
    - libexpat 2.7.3 haf25636_0
    - libffi 3.5.2 he5f378a_0
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.51.0 h8adb53f_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.6.0 h5503f6c_0
    - pip 25.3 pyh8b19718_0
    - python 3.12.12 h18782d2_1_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h892fb3f_3
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __osx >=11.0
    - libcxx >=19
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
  run_constrained:
    - libbrotlicommon 1.2.0 hc919400_1
test:
  imports:
    - brotli
about:
  home: http://github.com/google/brotli
  dev_url: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  recipe-maintainers:
    - CJ-Wright
    - h-vetinari
    - wesm
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251124.1.1
  remote_url: https://github.com/conda-forge/brotli-feedstock
  sha: 61563a5a99db058833a6397855bcafd36ff97905
