# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Nov 14 01:11:58 2025
# ------------------------------------------------

package:
  name: frozendict
  version: 2.4.7
source:
  fn: frozendict-2.4.7.tar.gz
  url: https://pypi.org/packages/source/f/frozendict/frozendict-2.4.7.tar.gz
  sha256: e478fb2a1391a56c8a6e10cc97c4a9002b410ecd1ac28c18d780661762e271bd
build:
  script: python -m pip install . --no-deps -vv
  number: '0'
  string: py312h4409184_0
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_osx-64 1024.3 llvm19_1_h3b512aa_9
    - cctools_osx-arm64 1024.3 llvm19_1_h5cc7f4e_9
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - cross-python_osx-arm64 3.12 54_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - ld64_osx-64 955.13 llvm19_1_h466f870_9
    - ld64_osx-arm64 955.13 llvm19_1_hcfa1dea_9
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcxx 21.1.5 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_1
    - libexpat 2.7.1 h21dd04a_0
    - libffi 3.5.2 h750e83c_0
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.51.0 h86bffb9_0
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.0 h230baf5_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.12 h74c2667_1_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_3
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - libexpat 2.7.1 hec049ff_0
    - libffi 3.5.2 he5f378a_0
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.51.0 h8adb53f_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.6.0 h5503f6c_0
    - pip 25.3 pyh8b19718_0
    - python 3.12.12 h18782d2_1_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h892fb3f_3
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  imports:
    - frozendict
about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict
extra:
  recipe-maintainers:
    - Marco-Sulla
    - ltalirz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251113.1.1
  remote_url: https://github.com/conda-forge/frozendict-feedstock
  sha: e85b9262d29895d39110e567bf33de0fb1975db7
