# This file created by conda-build 25.3.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Nov 12 19:35:13 2025
# ------------------------------------------------

package:
  name: certifi
  version: 2025.11.12
source:
  - folder: certifi
    sha256: d8ab5478f2ecd78af242878415affce761ca6bc54a22a27e026d7c25357c3316
    url: https://pypi.org/packages/source/c/certifi/certifi-2025.11.12.tar.gz
  - folder: boostrap_wheels
    sha256: c46efd13b6aa8279f33f2864459c8ce587ea6a1a59ee20de055868d8f7688f7f
    url: https://pypi.org/packages/py3/p/pip/pip-25.0.1-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: e3982f444617239225d675215d51f6ba05f845d4eec313da4418fdbb56fb27e3
    url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.8.0-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: 708e7481cc80179af0e556bbf0cc00b8444c7321e2700b8d8580231d13017248
    url: https://pypi.org/packages/py3/w/wheel/wheel-0.45.1-py3-none-any.whl
build:
  noarch: python
  number: '0'
  script:
    - cd certifi
    - /home/conda/feedstock_root/build_artifacts/certifi_1762976168352/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
      -m pip install . -vv
  script_env:
    - 'PYTHONPATH=/home/conda/feedstock_root/build_artifacts/certifi_1762976168352/work/boostrap_wheels:'
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - icu 75.1 he02047a_0
    - ld_impl_linux-64 2.44 h1aa0949_5
    - libexpat 2.7.1 hecca717_0
    - libffi 3.5.2 h9ec8514_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.51.0 hee844dc_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libstdcxx-ng 15.2.0 h4852527_7
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.6.0 h26f9b46_0
    - python 3.10.19 h3c07f61_2_cpython
    - readline 8.2 h8c095d6_2
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - python >=3.10
test:
  imports:
    - certifi
  requires:
    - python 3.10.*
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: http://certifi.io/
  license: ISC
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20251112.2.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: https://github.com/conda-forge/certifi-feedstock
  sha: 597df96383f98f66d050e51a1179339564717779
