# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Oct 13 15:32:18 2025
# ------------------------------------------------

package:
  name: fmt
  version: 12.0.0
source:
  url: https://github.com/fmtlib/fmt/archive/12.0.0.tar.gz
  sha256: aa3e8fbb6a0066c03454434add1f1fc23299e85758ceec0d7d2d974431481e40
build:
  number: '0'
  run_exports:
    - fmt >=12.0.0,<12.1.0a0
  string: h669d743_0
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - c-ares 1.34.5 hf13058a_0
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - cctools_osx-64 1024.3 llvm19_1_h3b512aa_5
    - cctools_osx-arm64 1024.3 llvm19_1_h5cc7f4e_5
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - clangxx_osx-arm64 19.1.7 h1728699_25
    - cmake 4.1.2 h29fc008_0
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 955.13 llvm19_1_h466f870_5
    - ld64_osx-arm64 955.13 llvm19_1_hcfa1dea_5
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcurl 8.14.1 h5dec5d8_0
    - libcxx 21.1.3 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_1
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.1 h21dd04a_0
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libnghttp2 1.67.0 h3338091_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h58003a5_1
    - libxml2 2.15.0 h23bb396_1
    - libxml2-16 2.15.0 h0ad03eb_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.4 h230baf5_0
    - rhash 1.4.6 h6e16a3a_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - libcxx 21.1.3 hf598326_0
  run:
    - __osx >=11.0
    - libcxx >=19
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
  downstreams:
    - libmambapy
about:
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  doc_url: https://fmt.dev/latest/
  dev_url: https://github.com/fmtlib/fmt
extra:
  recipe-maintainers:
    - bdice
    - h-vetinari
    - saraedum
    - tdegeus
    - vitaut
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251013.1.1
  remote_url: https://github.com/conda-forge/fmt-feedstock
  sha: f88e8807d167f7084616f716bfd303f63877a0f6
