# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Nov 13 17:20:29 2025
# ------------------------------------------------

package:
  name: tk
  version: 8.6.13
source:
  - url: https://downloads.sourceforge.net/tcl/tcl8.6.13-src.tar.gz
    folder: tcl8.6.13
    sha256: 43a1fae7412f61ff11de2cfd05d28cfc3a73762f354a417c62370a54e2caf066
  - url: https://downloads.sourceforge.net/tcl/tk8.6.13-src.tar.gz
    folder: tk8.6.13
    sha256: 2e65fa069a23365440a3c56c556b8673b5e32a283800d8d9b257e3f584ce0675
build:
  number: '3'
  track_features: null
  detect_binary_files_with_prefix: true
  run_exports:
    - tk >=8.6.13,<8.7.0a0
  ignore_run_exports_from: null
  string: h892fb3f_3
requirements:
  build:
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cctools_osx-64 1021.4 h508880d_0
    - cctools_osx-arm64 1021.4 hc3ac574_0
    - clang 18.1.8 default_h1323312_15
    - clang-18 18.1.8 default_hc369343_15
    - clang_impl_osx-arm64 18.1.8 hadf8e89_25
    - clang_osx-arm64 18.1.8 h1728699_25
    - compiler-rt 18.1.8 he914875_2
    - compiler-rt_osx-64 18.1.8 h138dee1_2
    - ld64_osx-64 954.16 h28b3ac7_0
    - ld64_osx-arm64 954.16 h750c29f_0
    - libclang-cpp18.1 18.1.8 default_hc369343_15
    - libcxx 21.1.5 h3d58e20_0
    - libiconv 1.18 h57a12c2_2
    - libllvm18 18.1.8 default_hc369343_10
    - liblzma 5.8.1 hd471939_2
    - libxml2 2.15.1 h23bb396_0
    - libxml2-16 2.15.1 h0ad03eb_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_hc369343_10
    - llvm-tools-18 18.1.8 default_hc369343_10
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.0 h230baf5_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run_constrained: []
  run:
    - __osx >=11.0
    - libzlib >=1.3.1,<2.0a0
test:
  files:
    - hello.tcl
  commands:
    - test -f "${PREFIX}/bin/tclsh"
    - test -f "${PREFIX}/bin/wish"
    - test -f "${PREFIX}/bin/tclsh8.6"
    - test -f "${PREFIX}/bin/wish8.6"
    - test -f "${PREFIX}/include/tcl.h"
    - test -f "${PREFIX}/include/tclDecls.h"
    - test -f "${PREFIX}/include/tclPlatDecls.h"
    - test -f "${PREFIX}/include/tclPlatDecls.h"
    - test -f "${PREFIX}/include/tclTomMathDecls.h"
    - test -f "${PREFIX}/include/tclTomMath.h"
    - test -f "${PREFIX}/include/tk.h"
    - test -f "${PREFIX}/include/tkDecls.h"
    - test -f "${PREFIX}/include/tkPlatDecls.h"
    - test -f "${PREFIX}/lib/libtcl8.6.dylib"
    - test -f "${PREFIX}/lib/libtclstub8.6.a"
    - test -f "${PREFIX}/lib/libtk8.6.dylib"
    - test -f "${PREFIX}/lib/libtkstub8.6.a"
    - tclsh hello.tcl
    - tclsh8.6 hello.tcl
    - wish hello.tcl
    - wish8.6 hello.tcl
about:
  home: http://www.tcl.tk/
  license: TCL
  license_family: BSD
  license_file: tcl8.6.13/license.terms
  summary: A dynamic programming language with GUI support.  Bundles Tcl and Tk.
  dev_url: https://github.com/tcltk/tk
extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - matthiasdiener
    - msarahan
    - ocefpaf
    - pelson
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251113.5.1
  remote_url: https://github.com/conda-forge/tk-feedstock
  sha: 4d61d0d6007eba31e189ff1355769df5e13419da
