# This file created by conda-build 25.7.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Sep  9 16:58:29 2025
# ------------------------------------------------

package:
  name: bzip2
  version: 1.0.8
source:
  url: https://gitlab.com/bzip2/bzip2/-/archive/bzip2-1.0.8/bzip2-bzip2-1.0.8.tar.gz
  sha256: db106b740252669664fd8f3a1c69fe7f689d5cd4b132f82ba82b9afba27627df
  patches:
    - patches/0001-cross.patch
    - patches/0002-Windows-Make-library-name-lowercase.patch
    - patches/0003-Windows-Add-dyn-lib-build-rename-libbz2_static.patch
build:
  number: '8'
  run_exports:
    - bzip2 >=1.0.8,<2.0a0
  string: hd037594_8
requirements:
  build:
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cctools_osx-64 1024.3 haa85c18_1
    - cctools_osx-arm64 1024.3 h65996a6_1
    - clang 19.1.7 default_h1323312_4
    - clang-19 19.1.7 default_hc369343_4
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - ld64_osx-64 955.13 hf1c22e8_1
    - ld64_osx-arm64 955.13 h59013cd_1
    - libclang-cpp19.1 19.1.7 default_hc369343_4
    - libcxx 21.1.0 h3d58e20_1
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libxml2 2.14.6 h23bb396_1
    - libxml2-16 2.14.6 h0ad03eb_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.2 h6e31bce_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - bzip2 --help
    - test -f ${PREFIX}/bin/bunzip2
    - test -f ${PREFIX}/bin/bzcat
    - test -f ${PREFIX}/bin/bzcmp
    - test -f ${PREFIX}/bin/bzdiff
    - test -f ${PREFIX}/bin/bzegrep
    - test -f ${PREFIX}/bin/bzfgrep
    - test -f ${PREFIX}/bin/bzgrep
    - test -f ${PREFIX}/bin/bzip2recover
    - test -f ${PREFIX}/bin/bzip2
    - test -f ${PREFIX}/bin/bzless
    - test -f ${PREFIX}/bin/bzmore
    - test -f ${PREFIX}/include/bzlib.h
    - test -f ${PREFIX}/lib/libbz2.a
    - test -f ${PREFIX}/lib/libbz2.dylib
about:
  home: https://gitlab.com/bzip2/bzip2
  license_family: BSD
  license_file: LICENSE
  license: bzip2-1.0.6
  summary: high-quality data compressor
  description: 'Bzip2 is a freely available high-quality data compressor. It typically

    compresses files to within 10% to 15% of the best available techniques,

    whilst being around twice as fast at compression and six times faster

    at decompression.

    '
  dev_url: https://gitlab.com/bzip2/bzip2
extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - msarahan
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250909.4.1
  remote_url: https://github.com/conda-forge/bzip2-feedstock
  sha: c19f23038caf2145a010d20e20514a2d4dd8f896
